<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ToolTikTok.Contracts\ToolTikTok.Contracts.csproj" />
    <ProjectReference Include="..\ToolTikTok.Automation\ToolTikTok.Automation.csproj" />
  </ItemGroup>
</Project>
