name: build

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore ToolTikTok.sln -m:1
      - name: Build
        run: dotnet build ToolTikTok.sln -c Release --no-restore -m:1
      - name: Test
        run: dotnet test ToolTikTok.sln -c Release --no-build -m:1
